### ISSUE TITLE
notifications 

### ISSUE THREAD

**Issue by Kolliiman** [Sov-Nation/dd_outlawalerts#16]
having trouble getting the notifications to send to the police it shows the color mark on the map but nothing from the local text

**Comment by DokaDoka** [comment]
Any errors on the client or server side? My best guess would be that it's not liking the server callback to find the scanner item quantity as that probably doesn't exist in your database.

This script is still pretty rough, I need to add an sql file to add that item and make the changes that would be make the outlaw blip work.

So I suspect the fix for this is to either add an item called `scanner` to the items database or modify 'dd_outlawalerts:Notify' to remove that callback and the quantity check.

But that might not be the issue so let me know if you have any errors.

**Comment by Kolliiman** [comment]
perfect thanks adding the scanner to the database worked :D
